### ISSUE TITLE
Better call to action in readme 

### ISSUE THREAD

**Issue by epugh** [querqy/chorus#26]
I like the call to action that this project https://github.com/simonw/datasette

**Comment by epugh** [comment]
Inspired by https://raw.githubusercontent.com/simonw/datasette/main/README.md and the Quepid README.

**Comment by epugh** [comment]
@flaxsearch and @renekrie I was looking at the github page for __Datasette__ and realizing how weak our opening README page is in terms of getting folks excited.    Inspired by the both the Quepid and Datasette Readmes, I started reworking the top of hte page:

https://github.com/querqy/chorus/tree/better_cta_readme

Obviously a work in progress, since I haven't figure out the best way to link to the online demo, or what the "three hard problems" to solve are.   I'd love feedback/ideas....    What would get you to download and try out Chorus????

**Comment by renekrie** [comment]
I think the most important thing will be to keep thee documentation apart from the README - just like Datasette, though I'd keep the README even more minimalistic than Datasette to avoid duplication. 

We had decided to use https://chorus.querqy.org fro documentation and we have a GitHub project for this https://github.com/querqy/chorus.querqy.org (auto-publishes to the website). The idea was to use Sphinx over GitHub because it's more powerful. I think the majority of the content should definitely live there - the call to (first) action could come from the README.

**Comment by vincetrumental** [comment]
Just a detail (don't know if it should go into README or/and in the proper documentation)
in the Useful Commands for Chorus section, add
"""
You can shut down your environment with: 
docker-compose stop
"""
in order to prevent user from assuming that "docker-compose down (-v)" is the opposite of "docker-compose up" and a proper way to simply shut down chorus.  And we could precise that docker-compose up will build AND start the environment , but --build option should only be used when an image rebuild is needed.
