### ISSUE TITLE
Investigate if we need a rules.txt on the filesystem

### ISSUE THREAD

**Issue by epugh** [querqy/chorus#8]
Currently have a `volumes/preliveCore/conf/rules.txt` file that appears to be needed to allow Querqy to start up.  With out it, I think Querqy blows up, or maybe SMUI does.

This file gets edited, which means when you do `git status` you constantly see it!  We really want to have it be in the `.gitignore`.

I thought about creative Git techniques like in this post: https://stackoverflow.com/questions/3319479/can-i-git-commit-a-file-and-ignore-its-content-changes but that looks very error prone!

**Comment by renekrie** [comment]
It looks like we are going to start work on https://github.com/querqy/querqy/issues/76 ('Rewriting the rewriter configuration') very soon. We will probably use an approach similar to the rewriter configuration in ES, which means that a rewriter needn't be configured until it is used - which might also help with this issue here.

**Comment by epugh** [comment]
Now storing in Zookeeper, which avoids the file system access issue.   Going to close as we have this solved for now.
